# Generated by Django 5.2.9 on 2025-12-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='profile_image',
        ),
    ]
