# Generated by Django 5.2.9 on 2025-12-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_authuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='default_profile.png', null=True, upload_to='profile_pics/'),
        ),
    ]
